### ISSUE TITLE
error in running training file

### ISSUE THREAD

**Issue by haiautoup** [taotaonice/FaceShifter#19]
Hi ,
I met this error when running the trai_AEI file

Traceback (most recent call last):
  File "train_AEI.py", line 131, in <module>
    ZY, Y_feats = arcface(F.interpolate(Y_aligned, [112, 112], mode='bilinear', align_corners=True))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 539, in _call_
    result = self.forward(*input, **kwargs)
  File "/home/user/FaceShifter/face_modules/model.py", line 141, in forward
    x = m(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 539, in _call_
    result = self.forward(*input, **kwargs)
  File "/home/user/FaceShifter/face_modules/model.py", line 76, in forward
    res = self.res_layer(x)
.......
......
  File "/home/user/.local/lib/python3.6/site-packages/apex/amp/utils.py", line 63, in maybe_half
    return x.half()
**RuntimeError: CUDA error: an illegal memory access was encountered**

Anyone met this error, and could show me the hint?

Thank you!!

**Comment by ocastan** [comment]
I had a similar issue. See [my comment](https://github.com/taotaonice/FaceShifter/issues/14#issuecomment-595614635) in issue #14 for the way I solved it.
